version: "3.9"
services:
  server:
    build: .
    ports:
      - "50051:50051"
    environment:
      - PORT = 50051
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=redis132
      - REDIS_DB=0
      - DB_DSN=postgres://postgres:postgres:5432/grpc-redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
    - REDIS_PASSWORD=redis132
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grpc-redis

