// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.27.3
// source: badge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Badge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Badge) Reset() {
	*x = Badge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Badge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Badge) ProtoMessage() {}

func (x *Badge) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Badge.ProtoReflect.Descriptor instead.
func (*Badge) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{0}
}

func (x *Badge) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Badge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBadgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBadgeRequest) Reset() {
	*x = GetBadgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBadgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBadgeRequest) ProtoMessage() {}

func (x *GetBadgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBadgeRequest.ProtoReflect.Descriptor instead.
func (*GetBadgeRequest) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{1}
}

func (x *GetBadgeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateBadgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateBadgeRequest) Reset() {
	*x = CreateBadgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBadgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBadgeRequest) ProtoMessage() {}

func (x *CreateBadgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBadgeRequest.ProtoReflect.Descriptor instead.
func (*CreateBadgeRequest) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBadgeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateBadgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateBadgeRequest) Reset() {
	*x = UpdateBadgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBadgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBadgeRequest) ProtoMessage() {}

func (x *UpdateBadgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBadgeRequest.ProtoReflect.Descriptor instead.
func (*UpdateBadgeRequest) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBadgeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBadgeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteBadgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBadgeRequest) Reset() {
	*x = DeleteBadgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBadgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBadgeRequest) ProtoMessage() {}

func (x *DeleteBadgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBadgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteBadgeRequest) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBadgeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteBadgeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteBadgeResponse) Reset() {
	*x = DeleteBadgeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badge_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBadgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBadgeResponse) ProtoMessage() {}

func (x *DeleteBadgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBadgeResponse.ProtoReflect.Descriptor instead.
func (*DeleteBadgeResponse) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBadgeResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetShopBadgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopID int64 `protobuf:"varint,1,opt,name=shopID,proto3" json:"shopID,omitempty"`
}

func (x *GetShopBadgeRequest) Reset() {
	*x = GetShopBadgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badge_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopBadgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopBadgeRequest) ProtoMessage() {}

func (x *GetShopBadgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopBadgeRequest.ProtoReflect.Descriptor instead.
func (*GetShopBadgeRequest) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{6}
}

func (x *GetShopBadgeRequest) GetShopID() int64 {
	if x != nil {
		return x.ShopID
	}
	return 0
}

type InvokeNsqResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopBadge *ShopBadge `protobuf:"bytes,1,opt,name=shopBadge,proto3" json:"shopBadge,omitempty"`
	Message   string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *InvokeNsqResponse) Reset() {
	*x = InvokeNsqResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badge_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvokeNsqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeNsqResponse) ProtoMessage() {}

func (x *InvokeNsqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeNsqResponse.ProtoReflect.Descriptor instead.
func (*InvokeNsqResponse) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeNsqResponse) GetShopBadge() *ShopBadge {
	if x != nil {
		return x.ShopBadge
	}
	return nil
}

func (x *InvokeNsqResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShopBadge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BadgeID int32  `protobuf:"varint,3,opt,name=badgeID,proto3" json:"badgeID,omitempty"`
	Badge   *Badge `protobuf:"bytes,4,opt,name=badge,proto3" json:"badge,omitempty"`
}

func (x *ShopBadge) Reset() {
	*x = ShopBadge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badge_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopBadge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopBadge) ProtoMessage() {}

func (x *ShopBadge) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopBadge.ProtoReflect.Descriptor instead.
func (*ShopBadge) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{8}
}

func (x *ShopBadge) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopBadge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopBadge) GetBadgeID() int32 {
	if x != nil {
		return x.BadgeID
	}
	return 0
}

func (x *ShopBadge) GetBadge() *Badge {
	if x != nil {
		return x.Badge
	}
	return nil
}

var File_badge_proto protoreflect.FileDescriptor

var file_badge_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x61, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62,
	0x61, 0x64, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x05, 0x42, 0x61, 0x64, 0x67, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61,
	0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x38,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22,
	0x2d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x44, 0x22, 0x5d,
	0x0a, 0x11, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x4e, 0x73, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x42, 0x61, 0x64, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x2e, 0x53,
	0x68, 0x6f, 0x70, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x42, 0x61,
	0x64, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x6d, 0x0a,
	0x09, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x61, 0x64, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x62, 0x61, 0x64, 0x67, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x62, 0x61, 0x64, 0x67, 0x65, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x05, 0x62, 0x61, 0x64, 0x67,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x2e,
	0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x05, 0x62, 0x61, 0x64, 0x67, 0x65, 0x32, 0x83, 0x03, 0x0a,
	0x0c, 0x42, 0x61, 0x64, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x42, 0x61, 0x64, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x62, 0x61, 0x64, 0x67,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0c, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x2e, 0x42, 0x61, 0x64, 0x67, 0x65, 0x22,
	0x00, 0x12, 0x38, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x64, 0x67, 0x65,
	0x12, 0x19, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x62, 0x61,
	0x64, 0x67, 0x65, 0x2e, 0x42, 0x61, 0x64, 0x67, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0b, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x64, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x62, 0x61, 0x64,
	0x67, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x2e, 0x42, 0x61,
	0x64, 0x67, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x61, 0x64, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61,
	0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x61, 0x64, 0x67, 0x65, 0x12, 0x1a, 0x2e,
	0x62, 0x61, 0x64, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x61, 0x64,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x62, 0x61, 0x64, 0x67,
	0x65, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x61, 0x64, 0x67, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a,
	0x09, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x4e, 0x73, 0x71, 0x12, 0x1a, 0x2e, 0x62, 0x61, 0x64,
	0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x62, 0x61, 0x64, 0x67, 0x65, 0x2e, 0x49,
	0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x4e, 0x73, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x62, 0x61, 0x64, 0x67, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_badge_proto_rawDescOnce sync.Once
	file_badge_proto_rawDescData = file_badge_proto_rawDesc
)

func file_badge_proto_rawDescGZIP() []byte {
	file_badge_proto_rawDescOnce.Do(func() {
		file_badge_proto_rawDescData = protoimpl.X.CompressGZIP(file_badge_proto_rawDescData)
	})
	return file_badge_proto_rawDescData
}

var file_badge_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_badge_proto_goTypes = []interface{}{
	(*Badge)(nil),               // 0: badge.Badge
	(*GetBadgeRequest)(nil),     // 1: badge.GetBadgeRequest
	(*CreateBadgeRequest)(nil),  // 2: badge.CreateBadgeRequest
	(*UpdateBadgeRequest)(nil),  // 3: badge.UpdateBadgeRequest
	(*DeleteBadgeRequest)(nil),  // 4: badge.DeleteBadgeRequest
	(*DeleteBadgeResponse)(nil), // 5: badge.DeleteBadgeResponse
	(*GetShopBadgeRequest)(nil), // 6: badge.GetShopBadgeRequest
	(*InvokeNsqResponse)(nil),   // 7: badge.InvokeNsqResponse
	(*ShopBadge)(nil),           // 8: badge.ShopBadge
}
var file_badge_proto_depIdxs = []int32{
	8, // 0: badge.InvokeNsqResponse.shopBadge:type_name -> badge.ShopBadge
	0, // 1: badge.ShopBadge.badge:type_name -> badge.Badge
	1, // 2: badge.BadgeService.GetBadge:input_type -> badge.GetBadgeRequest
	2, // 3: badge.BadgeService.CreateBadge:input_type -> badge.CreateBadgeRequest
	3, // 4: badge.BadgeService.UpdateBadge:input_type -> badge.UpdateBadgeRequest
	4, // 5: badge.BadgeService.DeleteBadge:input_type -> badge.DeleteBadgeRequest
	6, // 6: badge.BadgeService.GetShopBadge:input_type -> badge.GetShopBadgeRequest
	6, // 7: badge.BadgeService.InvokeNsq:input_type -> badge.GetShopBadgeRequest
	0, // 8: badge.BadgeService.GetBadge:output_type -> badge.Badge
	0, // 9: badge.BadgeService.CreateBadge:output_type -> badge.Badge
	0, // 10: badge.BadgeService.UpdateBadge:output_type -> badge.Badge
	5, // 11: badge.BadgeService.DeleteBadge:output_type -> badge.DeleteBadgeResponse
	8, // 12: badge.BadgeService.GetShopBadge:output_type -> badge.ShopBadge
	7, // 13: badge.BadgeService.InvokeNsq:output_type -> badge.InvokeNsqResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_badge_proto_init() }
func file_badge_proto_init() {
	if File_badge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_badge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Badge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBadgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBadgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBadgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badge_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBadgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badge_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBadgeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badge_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShopBadgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badge_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvokeNsqResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_badge_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopBadge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_badge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_badge_proto_goTypes,
		DependencyIndexes: file_badge_proto_depIdxs,
		MessageInfos:      file_badge_proto_msgTypes,
	}.Build()
	File_badge_proto = out.File
	file_badge_proto_rawDesc = nil
	file_badge_proto_goTypes = nil
	file_badge_proto_depIdxs = nil
}
